### PR TITLE
Event subscription

### PR DESCRIPTION
**Pull request by MattsCurrie**

### CODE REVIEW

**Comment by MattsCurrie** [comment]
Isn't our app beautiful? :')

**Comment by ctakasakaubc** [comment]
Looks good, gotta work on the build process ;(

**Comment by CarsonPerreaux** [comment]
The app looks quite good thus far

**Comment by daihuyang** [comment]
good work guys

**Comment by ctakasakaubc** [comment]
Hold up, we gotta make sure to have the updated .gitignore

**Comment by daihuyang** [comment]
9 million changes for Matthew, that was tons of work！

**Comment by ctakasakaubc** [comment]
> 
> 
> 9 million changes for Matthew, that was tons of work！

yeah, I'm not sure how his gitignore didn't update, must have been cause I updated it on a pruned branch

**Comment by CarsonPerreaux** [comment]
> Hold up, we gotta make sure to have the updated .gitignore

That's a good idea, good thinking Callum

**Comment by CarsonPerreaux** [comment]
Looks great fellas

**Comment by daihuyang** [comment]
project turns out good

**Pull request merged**
