### PR TITLE
Callum reqs7

### PR DESCRIPTION
**Pull request by ctakasakaubc**

### CODE REVIEW

**Comment by ctakasakaubc** [comment]
wait, we still need to figure out how to link Jupyter to the kernel I think.

**Comment by MattsCurrie** [comment]
Maybe we could spend more time with NodeJs as a group to figure stuff out.

**Comment by CarsonPerreaux** [comment]
I like the thought of spending more time with nodeJS as a group

**Comment by daihuyang** [comment]
lets spend more time on Jupiter notebook

**Pull request merged**
