### PR TITLE
Andrew reqs10

### PR DESCRIPTION
**Pull request by daihuyang**
behavior pack commit

### CODE REVIEW

**Comment by MattsCurrie** [comment]
Behavior pack changes aren't absolute with the agent unfortunately

**Comment by ctakasakaubc** [comment]
hah, wolves are weird now

**Comment by CarsonPerreaux** [comment]
We should make sure we use US or Canadian grammar when writing function names

**Comment by daihuyang** [comment]
I can not spell in American grammar sadly.

**Pull request merged**
