### PR TITLE
Http server mee carson

### PR DESCRIPTION
**Pull request by ctakasakaubc**

### CODE REVIEW

**Comment by MattsCurrie** [comment]
I like the styling work. We are going to have to add "/connect localhost:8765" somewhere on the HTML.

**Comment by ctakasakaubc** [comment]
ahh yea, the buttons are adding up, maybe we can throw it on the bottom as well

**Comment by CarsonPerreaux** [comment]
nice work, I can keep working on the html to work with the 3005 if there's more you want

**Comment by ctakasakaubc** [comment]
yeh, also make sure my conflict resolution worked properly

**Pull request merged**
