### PR TITLE
Local server matt

### PR DESCRIPTION
**Pull request by MattsCurrie**
beautiful beautiful code,

### CODE REVIEW

**Comment by MattsCurrie** [comment]
Let me know if you are having issues opening the web page within minecraft. I had to mess around with my cmd to get it working initially

**Comment by ctakasakaubc** [comment]
next up is merging this with the "this-that" app

**Comment by daihuyang** [comment]
cool stuff

**Comment by CarsonPerreaux** [comment]
sounds like a solid plan to me!

**Pull request merged**
