### PR TITLE
changes to CSS and html. Made structure easier to implement Javascipt…

### PR DESCRIPTION
**Pull request by CarsonPerreaux**
… functionality

### CODE REVIEW

**Comment by ctakasakaubc** [comment]
lovely, we got that internal scrolling now!

**Comment by MattsCurrie** [comment]
Good dynamic page sizing

**Comment by CarsonPerreaux** [comment]
I still need to implement a bit of Javascript and make the background images easier to resize

**Comment by daihuyang** [comment]
layout is neat

**Pull request merged**
