### PR TITLE
run button added

### PR DESCRIPTION
**Pull request by daihuyang**

### CODE REVIEW

**Comment by MattsCurrie** [comment]
Button styling looked good. Something we will need to do is decide on whether we want to use relative or absolute positioning

**Comment by ctakasakaubc** [comment]
gotta use the proper HTML name-format from now on, I'll refactor later.

**Comment by daihuyang** [comment]
we need to discuss the sizes and position for all the type boxes and buttons

**Comment by CarsonPerreaux** [comment]
I think relative would be best for positioning, but obviously if a certain element needs to be we can make it absolute in some cases!

**Pull request merged**
