### PR TITLE
Callum branch

### PR DESCRIPTION
**Pull request by ctakasakaubc**

### CODE REVIEW

**Comment by CarsonPerreaux** [comment]
A lot of requirements have changed since our last document

**Comment by daihuyang** [comment]
It would be good if we find a database that can handle Json objects

**Comment by MattsCurrie** [comment]
Local Mongo DB would make the most sense if it is feasible to run in our electron app

**Comment by ctakasakaubc** [comment]
yeah I'll get a MongoDB up soon

**Pull request merged**
