### PR TITLE
Matt behavior

### PR DESCRIPTION
**Pull request by MattsCurrie**
Code spent attempting to alter the behavior of the agent mob. Unfortunately, the Agent mob doesn't follow the standard movement rules that the other mobs do and, as such, we cannot change their movement to be like that of a wolf's.

### CODE REVIEW

**Comment by ctakasakaubc** [comment]
weird that we can't get the agent working, must be something to do with how owner is asigned?

**Comment by daihuyang** [comment]
npm installing is frustrating

**Comment by CarsonPerreaux** [comment]
We can add to the instructions as we go

**Comment by MattsCurrie** [comment]
> npm installing is frustrating

100%

**Pull request merged**
