### PR TITLE
Andrew reqs7

### PR DESCRIPTION
**Pull request by daihuyang**

### CODE REVIEW

**Comment by ctakasakaubc** [comment]
hey Andrew, you don't need to look at that AI textbook anymore.

**Comment by MattsCurrie** [comment]
When you get a chance, could you ask Jeff to get his thoughts on using a bayesian network in data visualization

**Comment by CarsonPerreaux** [comment]
Electron will give us a solid foundation to succeed with this project

**Comment by daihuyang** [comment]
Nice I don't need the book anymore

**Comment by ctakasakaubc** [comment]
blargy

**Pull request merged**
