### PR TITLE
Jsonl database

### PR DESCRIPTION
**Pull request by MattsCurrie**

### CODE REVIEW

**Comment by ctakasakaubc** [comment]
Woohoo, out with annoying csv headers!

**Comment by ctakasakaubc** [comment]
Although, we will have to clean this a bit in JS, ya?

**Comment by MattsCurrie** [comment]
Yeah, I think we will need to bugfix some JS stuff

**Comment by MattsCurrie** [comment]
Bright side is that I think that pandas works well with JSON lines. We will just have to do some cleaning before we create the dataframe

**Comment by CarsonPerreaux** [comment]
Yeah I can definitely clean some JS up, as well as adding some React

**Pull request merged**
