### PR TITLE
Andrewreqs9

### PR DESCRIPTION
**Pull request by daihuyang**

### CODE REVIEW

**Comment by CarsonPerreaux** [comment]
It was weird answering old questions for our new project but  it had to be done! great work

**Comment by daihuyang** [comment]
Plenty requirements have changed since last documentations commit.

**Comment by MattsCurrie** [comment]
Yeah the requirements for our previous plan were incredibly different than now. I think the websocket programming is going to be fun

**Comment by ctakasakaubc** [comment]
hopefully we can get a websocket test soon

**Pull request merged**
