### PR TITLE
Http server host python output

### PR DESCRIPTION
**Pull request by ctakasakaubc**

### CODE REVIEW

**Comment by ctakasakaubc** [comment]
Hmm, we're close to being ready, just that Python injection and some styling stuff left

**Comment by ctakasakaubc** [comment]
Should we refactor to update our JQuery import soon?

**Comment by MattsCurrie** [comment]
Impressive how we got this python kernel working so well in so few lines

**Comment by CarsonPerreaux** [comment]
beautifully executed merge

**Comment by CarsonPerreaux** [comment]
I'll be sure to branch off of the weekly branches from now on 💯

**Comment by daihuyang** [comment]
cool stuff

**Pull request merged**
