### PR TITLE
Jsonl database

### PR DESCRIPTION
**Pull request by MattsCurrie**

### CODE REVIEW

**Comment by ctakasakaubc** [comment]
Bueno, kind of spits in the face of JSONL but it works haha :P

**Comment by MattsCurrie** [comment]
Yeaaahhhh, but it is a necessary spitting to make reading the files into pandas easier

**Comment by CarsonPerreaux** [comment]
Looks good to me!

**Comment by CarsonPerreaux** [comment]
good job Matt

**Pull request merged**
