### PR TITLE
Py event definition

### PR DESCRIPTION
**Pull request by ctakasakaubc**

### CODE REVIEW

**Comment by daihuyang** [comment]
maybe we should figure the light level next week

**Comment by CarsonPerreaux** [comment]
We can make select elements better in CSS

**Comment by MattsCurrie** [comment]
I think there is a folder with textures we can use to make the styling more minecraft-like ya know

**Comment by ctakasakaubc** [comment]
Matt you gotta fetch again, I even set the font to Mojangle!

**Comment by ctakasakaubc** [comment]
> 
> 
> We can make select elements better in CSS

yea, I was a bit quick on the styling, but it's mostly there

**Pull request merged**
