### PR TITLE
Adding dummy data

### PR DESCRIPTION
**Pull request by ctakasakaubc**

### CODE REVIEW

**Comment by MattsCurrie** [comment]
Sweet, that should help with testing things

**Comment by MattsCurrie** [comment]
Also, I think we should move into a better database in the future. Maybe JSON L is the way to go since other groups seem to want to use that. Otherwise SQLite is my choice.

**Comment by daihuyang** [comment]
good stuff

**Comment by CarsonPerreaux** [comment]
We could maybe try using a blockchain instead of SQL to store the data ;)

**Pull request merged**
