### PR TITLE
Carson reqs10

### PR DESCRIPTION
**Pull request by CarsonPerreaux**

### CODE REVIEW

**Comment by MattsCurrie** [comment]
@CarsonPerreaux its gonna be best to leave the agent movement stuff to a different project as I think reworking the behavior of the agent is part of the source code which we don't have access to

**Comment by ctakasakaubc** [comment]
Should try to change how NPCs path to see if it's just because agents are special

**Comment by daihuyang** [comment]
we should start to figure out how to access the light level in MME

**Comment by CarsonPerreaux** [comment]
Remove OneDrive from Desktop so there's no file issues

**Comment by MattsCurrie** [comment]
> we should start to figure out how to access the light level in MME

I don't think we can do that with the current implementations. I think that was something Jeff was doing as part of innovation week.

**Pull request merged**
