### PR TITLE
Http server host styling

### PR DESCRIPTION
**Pull request by CarsonPerreaux**

### CODE REVIEW

**Comment by MattsCurrie** [comment]
Solid Styling. It looks good at the dimensions in game

**Comment by ctakasakaubc** [comment]
Much spiffier than it was, just gotta get that pillbox in

**Comment by MattsCurrie** [comment]
Pillbox selection is probably gonna be a bit of work to style with minecraft textures

**Comment by CarsonPerreaux** [comment]
I'm thinking I'll use bootstrap and jQuery for the pillbox/drop-down menu

**Pull request merged**
